### ISSUE TITLE
make the robot fly

### ISSUE THREAD

**Issue by im-a-robo** [frc-862/rookieTrainingRepo#1]

**Comment by DerpTaterTot** [comment]
making a robot fly will be very beneficial in our competition

**Comment by HeeistHo** [comment]
nah i dont think the robot should fly, we need flippers and a motor for water game

**Comment by IronManIK** [comment]
but funny robot!!!111!1!
wings?????

**Comment by Burh826** [comment]
is this fr or on god

**Comment by TurtleMaster29** [comment]
> is this fr or on god

its on god fr
