### ISSUE TITLE
good task

### ISSUE THREAD

**Issue by im-a-robo** [frc-862/rookieTrainingRepo#2]

**Comment by HeeistHo** [comment]
very good yes indeed

**Comment by Burh826** [comment]
im begging please tell me if this is fr or ong

**Comment by HeeistHo** [comment]
its an onfr

**Comment by HeeistHo** [comment]
line 26 doesnt have a semicolon, the robot exploded

**Comment by Meh243** [comment]
this task is poo poo >:(
